service: cron-job-sls-framework

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: "*"

package:
 patterns:
    - '!package-lock.json'
    - '!node_modules/**'
    - '!package.json'
    - '!README.md'

functions:
  hello:
    handler: handler.hello
    name: cronJob-sls
    events:
      - schedule: rate(2 minutes)