service: cron-job-sls-framework

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

package:
 patterns:
    - '!package-lock.json'
    - '!node_modules/**'

functions:
  hello:
    handler: handler.hello